name: PmemCI
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Installs dependencies
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/install_dependencies.sh"
          "${GITHUB_WORKSPACE}/.github/install_dependencies.sh"

      - name: Set up cmake
        run: mkdir build; cd build; cmake ../

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          exclude_check: ./vcpkg/
          std: c++17
          output_file: ./CppCheckReport.txt
          other_options: -v --suppress=missingIncludeSystem

      - name: publish report
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'

      - name: Run cmake
        run: cd build; cmake --build .

      - name: Run tests
        run: cd build; ctest -R pmemdb_tests
